#  Copyright 2018 U.C. Berkeley RISE Lab
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: ebs-instances
spec:
  image: kope.io/k8s-1.11-debian-stretch-amd64-hvm-ebs-2018-08-17
  machineType: r4.large
  maxSize: NUM_DUMMY
  minSize: NUM_DUMMY
  rootVolumeSize: 32
  role: Node
  nodeLabels:
    role: ebs
  subnets:
    - us-east-1a
  volumes:
    - device: /dev/xvdb
      encrypted: false
      size: 64
      type: gp2
    - device: /dev/xvdc
      encrypted: false
      size: 64
      type: gp2
    - device: /dev/xvdd
      encrypted: false
      size: 64
      type: gp2
    - device: /dev/xvde
      encrypted: false
      size: 64
      type: gp2
  volumeMounts:
    - device: /dev/xvdb
      filesystem: ext4
      path: /ebs/ebs_0
    - device: /dev/xvdc
      filesystem: ext4
      path: /ebs/ebs_1
    - device: /dev/xvdd
      filesystem: ext4
      path: /ebs/ebs_2
    - device: /dev/xvde
      filesystem: ext4
      path: /ebs/ebs_3
