#  Copyright 2018 U.C. Berkeley RISE Lab
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: v1
kind: Pod
metadata:
  name: ebs-pod-NUM_DUMMY
  labels: 
    role: ebs
spec:
  containers:
    - name: ebs-container
      image: vsreekanti/anna
      env: 
      - name: SERVER_TYPE
        value: "2"
      - name: ROUTING_IPS
        value: ROUTING_IPS_DUMMY
      - name: SEED_IP
        value: SEED_IP_DUMMY
      - name: MON_IPS
        value: MON_IPS_DUMMY
      volumeMounts:
      - mountPath: /ebs/ebs_0
        name: ebs0
      - mountPath: /ebs/ebs_1
        name: ebs1
      - mountPath: /ebs/ebs_2
        name: ebs2
      - mountPath: /ebs/ebs_3
        name: ebs3
  nodeSelector:
    role: ebs
    podid: ebs-NUM_DUMMY
  volumes:
  - name: ebs0
    awsElasticBlockStore:
      volumeID: VOLUME_DUMMY_0
      fsType: ext4
  - name: ebs1
    awsElasticBlockStore:
      volumeID: VOLUME_DUMMY_1
      fsType: ext4
  - name: ebs2
    awsElasticBlockStore:
      volumeID: VOLUME_DUMMY_2
      fsType: ext4
  - name: ebs3
    awsElasticBlockStore:
      volumeID: VOLUME_DUMMY_3
      fsType: ext4
  restartPolicy: Never
