monitoring:
  mgmt_ip: 127.0.0.1
  ip: 127.0.0.1
routing:
  monitoring: 
      - 127.0.0.1
  ip: 127.0.0.1
user:
  monitoring:
      - 127.0.0.1
  routing: 
      - 127.0.0.1
  ip: 127.0.0.1
server:
  monitoring:
      - 127.0.0.1
  routing: 
      - 127.0.0.1
  seed_ip: 127.0.0.1
  public_ip: 127.0.0.1
  private_ip: 127.0.0.1
  mgmt_ip: "NULL"
ebs: ./
threads:
  memory: 4
  ebs: 4
  shared-memory: 4
  routing: 4
  benchmark: 4
replication:
  memory: 1
  ebs: 0
  shared-memory: 0
  minimum: 1
  local: 1
